"""BigFrame"""
x1 = input().rstrip()
x2 = input().rstrip()
x3 = input().rstrip()
x4 = input().rstrip()
x5 = input().rstrip()
y1 = len(x1)
y2 = len(x2)
y3 = len(x3)
y4 = len(x4)
y5 = len(x5)
z = max(y1,y2,y3,y4,y5)
print("*"*(z+4))
print(f"* {x1}",end="")
print(" "*(z-(len(x1)))+" *")
print(f"* {x2}",end="")
print(" "*(z-(len(x2)))+" *")
print(f"* {x3}",end="")
print(" "*(z-(len(x3)))+" *")
print(f"* {x4}",end="")
print(" "*(z-(len(x4)))+" *")
print(f"* {x5}",end="")
print(" "*(z-(len(x5)))+" *")
print("*"*(z+4))
